name: Scheduled Health Check

on: 
  schedule:
   - cron: '*/5 * * * *'

jobs:
  environment-health-check:
    runs-on: ubuntu-latest
    env: 
      amt_password: ${{ secrets.AMTPASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests
        id: cypress
        run: npx cypress run --env amt_password=$amt_password

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: Cypress HTML Report
          path: /home/runner/work/AMTDirect-Health-Check/AMTDirect-Health-Check/cypress/reports/html/index.html        

      - name: Send email with results if tests fail
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SENDGRID_USERNAME }}
          password: ${{ secrets.SENDGRID_PASSWORD }}
          subject: ALERT - AMTDirect Environment Inaccessible
          to: kaylin.kilby@mrisoftware.com, christy.kisiah@mrisoftware.com, amanda.ramjohn@mrisoftware.com, aj.babcock@mrisoftware.com, preston.rockholt@mrisoftware.com, asad.udaipurwala@mrisoftware.com, richard.reynolds@mrisoftware.com, tien.nguyen@mrisoftware.com
          cc: qa.amtdirect@dsinnovators.com
          from: QA AMTDirect
          body: |
           Dear Team, 

           This is an automated email to inform you that one or multiple environments may be inaccessible. Additional information are provided in the attached report.

           NOTE: Please download the HTML file for viewing it.

           Regards,
           QA Team
            
          attachments: |
            /home/runner/work/AMTDirect-Health-Check/AMTDirect-Health-Check/cypress/reports/html/index.html
              
